# Generated by Django 3.1.5 on 2021-01-22 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('firm_name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('aadhar', models.CharField(blank=True, max_length=12, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=30, null=True)),
                ('total', models.FloatField()),
                ('gst_percent', models.FloatField()),
                ('discount_percent', models.FloatField()),
                ('discount_amount', models.FloatField(blank=True)),
                ('gst_amount', models.FloatField(blank=True)),
                ('amount', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=8)),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(max_length=122)),
                ('price', models.FloatField()),
                ('cost', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='orders.order')),
            ],
        ),
    ]
