# Generated by Django 3.1.5 on 2021-01-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210117_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='art_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
